import "./globals.css";
import { Manrope } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title:
    "GPT-3 Landing Page | Landing Page Developped by Rifky Niyas, Designed by A.R. Shakir",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-dark text-white`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
